### ISSUE TITLE
ReactiveCocoa spec needs pushed for v4.0.0-alpha.3

### ISSUE THREAD

**Issue by JRHeaton** [ashfurrow/ReactiveCocoa#3]
Today, @ashfurrow pointed out to me that a pod spec for RAC 4 alpha 3 does in fact exist [here](https://github.com/CocoaPods/Specs/blob/master/Specs/ReactiveCocoa/4.0.0-alpha-3/ReactiveCocoa.podspec.json). However, I've noticed that it's not public on trunk. The latest available RAC to install is `4.0.4-alpha-1`.

```sh

ReactiveCocoa
    - Versions:
    [shortened]
      - 2.5 (2015-04-20 17:06:39 UTC)
      - 3.0.0 (2015-09-15 15:53:22 UTC)
      - 3.0.0-alpha.1 (2015-01-13 14:07:48 UTC)
      - 3.0.0-swift2 (2015-09-14 13:35:11 UTC)
      - 3.0-alpha.3 (2015-04-06 15:54:31 UTC)
      - 3.0-beta.6 (2015-05-23 16:32:27 UTC)
      - 3.0-beta.9 (2015-07-10 14:18:25 UTC)
      - 3.0-RC.1 (2015-07-21 13:55:36 UTC)
      - 4.0.0-alpha-1 (2015-09-16 00:35:23 UTC)
      - 4.0.0-alpha-2 (2015-10-25 21:25:32 UTC)
      - 4.0.0-alpha-3 (2015-10-25 21:30:57 UTC)
      - 4.0.1-alpha-1 (2015-09-16 13:31:48 UTC)
      - 4.0.2-alpha-1 (2015-09-16 21:51:59 UTC)
      - 4.0.3-alpha-1 (2015-10-25 21:21:55 UTC)
      - 4.0.4-alpha-1 (2015-10-25 21:48:00 UTC)
    - Owners:
      - Nikolay Kasyanov <corrmage@gmail.com>
      - Tony Arnold <tony@thecocoabots.com>
      - Ash Furrow <ash@ashfurrow.com>
      - Syo Ikeda <suicaicoca@gmail.com>
      - Bjarke Søndergaard <bhsgaard@gmail.com>
      - Mathew Huusko V <mhuusko5@gmail.com>
      - Kyle Fuller <kyle@fuller.li>
      - Gabriele Petronella <gabriele@buildo.io>
      - Mark Sands <marksands07@gmail.com>
```

I'm setting up a public library which can be installed with, and install its dependencies through, either CocoaPods _or_ Carthage. My `Cartfile` is able to point directly to the `v4.0.0-alpha.3` tag on the RAC repo, but I'm unable to install the matching RAC source via pods since it's not on trunk. Since there are breaking changes across these alpha versions of RAC, the source for the library can't compile via pods, while it can on Carthage.

It would be very great if the `4.0.0-alpha-3` spec could be pushed :)

**Comment by ashfurrow** [comment]
That's odd – `4.0.0-alpha-3` _is_ on trunk. It was pushed yesterday – could you try running `pod repo update` and trying again?

**Comment by JRHeaton** [comment]
Wow. Monday moment. I was not setting the version specifier properly. I had it on `4.0.4-alpha-3`, which is incorrect. Sorry about that!
